import test from 'node:test';import assert from 'node:assert/strict';
import {vega,vegaLite} from '../vendor/index.js';import {acquisitionSpec,pairedSpec,pairedData,slopesSpec} from '../src/study-specs.js';
const group={metric:'time',summary:{n:4,nRuns:4,mean:50,low:-5,high:105},people:['A','B','C','D'].map((p,i)=>({participant_id:p,participant_label:p,saved:i*30,free:600,edge:600-i*30,nRuns:1})),runs:['A','B','C','D'].map((p,i)=>({participant_id:p,participant_label:p,dataset_id:p+':r1',dataset_label:p+' Run 1',free:600,edge:600-i*30,saved:i*30,nFree:4,nEdge:4}))};
for(const name of ['combined','separate','paired','accuracy','slopes'])test('real populated Vega render: '+name,async()=>{
 const spec=name==='paired'?pairedSpec(group):name==='accuracy'?pairedSpec({...group,metric:'accuracy'}):name==='slopes'?slopesSpec():acquisitionSpec({stageFilter:name==='separate'?'horizontal':null,selected:'A:r1'});
 spec.datasets=name==='paired'||name==='accuracy'?pairedData(group):{trials:[{task:'horizontal',acquisition_ms:600,index_difficulty:2,dataset_id:'A:r1',student_color:'#397aac',hit:true}],fit:[{task:'horizontal',key:'a',settings:'native',index_difficulty:1,acquisition_ms:500},{task:'horizontal',key:'a',settings:'native',index_difficulty:4,acquisition_ms:800}],bands:[{task:'horizontal',key:'a',index_difficulty:1,low:400,high:600},{task:'horizontal',key:'a',index_difficulty:4,low:700,high:950}],selectedFit:[],people:[]};
 const compiled=vegaLite.compile(spec).spec,view=new vega.View(vega.parse(compiled),{renderer:'none'});await view.runAsync();const svg=await view.toSVG();assert.ok(svg.includes('<path'));view.finalize();
});
test('mean bands are ranged areas with separate low/high channels',()=>{const s=acquisitionSpec();assert.equal(s.layer[0].mark.type,'area');assert.equal(s.layer[0].encoding.y.field,'low');assert.equal(s.layer[0].encoding.y2.field,'high');for(const l of s.layer)assert.equal(l.mark.clip,true);});
test('paired effects have a horizontal zero reference and per-participant rows',()=>{const s=pairedSpec(group);assert.equal(s.hconcat.length,2);assert.equal(s.hconcat[1].layer[0].encoding.x.datum,0);assert.equal(s.hconcat[1].layer[2].encoding.y.field,'row');});
