import test from 'node:test';import assert from 'node:assert/strict';
import {analyze,finiteRows,regressionGroups,boundaryAnalysis,cleanRows,bootstrapMean,runKey} from '../src/study.js';
const row=(p,i,extra={})=>({id:`${p}-${i}`,participant_id:p,participant_label:p,run_id:'r1',run_number:1,task:'horizontal',app_version:'1.3.0',input_mode:'native',device:'unspecified',gain:1,perturbation:'normal',jitter_css_px:0,attempt:1,hit:true,practice:false,index_difficulty:1+i%4,distance:100*(1+i%4),nominal_distance:100*(1+i%4),approach_width:20+(i%4)*10,target_w:20+(i%4)*10,condition:'c'+i%4,variant:'strips',acquisition_ms:200+60*(1+i%4),...extra});
const data=()=>Array.from({length:6},(_,p)=>Array.from({length:16},(_,i)=>row('p'+p,i,{acquisition_ms:200+p*30+(40+p*8)*(1+i%4)}))).flat();
const approx=(a,b)=>assert.ok(Math.abs(a-b)<1e-8,`${a} ≠ ${b}`);
test('participant-weighted slope and confidence bands use all independent identities',()=>{const rows=data(),r=regressionGroups(rows);approx(r.fits[0].b,60);assert.equal(r.fits[0].nPeople,6);assert.equal(r.bands.length,41);assert.ok(r.fits[0].bLow<60&&r.fits[0].bHigh>60);assert.deepEqual(r,regressionGroups(rows));});
test('repeating one participant does not increase that participant’s weight or independent N',()=>{const rows=data(),duplicates=rows.filter(r=>r.participant_id==='p0').map(r=>({...r,id:r.id+'repeat',run_id:'r2'})),a=regressionGroups(rows),b=regressionGroups([...rows,...duplicates]);approx(a.fits[0].b,b.fits[0].b);assert.equal(a.fits[0].nPeople,b.fits[0].nPeople);approx(a.fits[0].bLow,b.fits[0].bLow);});
test('a selected run gets a descriptive fit without a spurious participant interval',()=>{const r=regressionGroups(data().filter(r=>r.participant_id==='p0'));assert.equal(r.fits.length,1);assert.equal(r.bands.length,0);assert.equal(r.fits[0].bLow,null);});
test('all reference rows survive cutoff and current-cutoff sensitivity uses the same source',()=>{const rows=data();rows[0]={...rows[0],acquisition_ms:25000};const before=JSON.stringify(rows),a=analyze(rows,{cutoff:1000,replicates:100});assert.equal(a.dataset.hidden,1);assert.equal(a.dataset.referenceTrials,96);assert.equal(JSON.stringify(rows),before);assert.notEqual(a.filtered.fits[0].b,a.reference.fits[0].b);});
test('misses, retries, practice and hard boundaries cannot enter Fitts timing fits',()=>{const rows=[...data(),row('p',0,{variant:'menu-edge',index_difficulty:null}),row('p',1,{hit:false,acquisition_ms:99999}),row('p',2,{attempt:2}),row('p',3,{practice:true})];const r=regressionGroups(finiteRows(rows));assert.equal(r.fits[0].nTrials,96);});
test('separate input/device/gain/protocol groups stay separate',()=>{const rows=data(),r=regressionGroups([...rows,...rows.map(r=>({...r,id:r.id+'v',input_mode:'virtual'}))]);assert.equal(r.fits.length,2);});
function pair(p,run='r1',saved=100,extra={}){return ['floating','edge'].flatMap((side,s)=>Array.from({length:4},(_,i)=>row(p,i,{...extra,id:`${p}-${run}-${side}-${i}`,run_id:run,task:'interfaces',variant:'menu-'+side,condition:'menu-'+side+'-control',index_difficulty:s?null:3,acquisition_ms:s?800-saved:800,input_mode:'virtual'})));}
test('boundary effect sign and participant averaging are explicit',()=>{const rows=[...pair('p0','r1',100),...pair('p0','r2',300),...pair('p1','r1',0),...pair('p2','r1',100),...pair('p3','r1',100)],g=boundaryAnalysis(rows).timing[0];assert.equal(g.summary.n,4);assert.equal(g.summary.nRuns,5);approx(g.summary.mean,100);assert.equal(g.people.find(p=>p.participant_id==='p0').saved,200);assert.ok(g.summary.low<=g.summary.mean&&g.summary.high>=g.summary.mean);});
test('accuracy denominator stays unfiltered and includes all-miss pairs',()=>{const rows=pair('p');rows[0].hit=false;rows[0].acquisition_ms=10000;const a=boundaryAnalysis(rows,1000),b=boundaryAnalysis(rows,Infinity);assert.deepEqual(a.accuracy,b.accuracy);approx(a.accuracy[0].summary.free,25);rows.forEach(r=>{if(r.variant==='menu-edge')r.hit=false;});const c=boundaryAnalysis(rows);assert.equal(c.timing.length,0);assert.equal(c.accuracy.length,1);});
test('input mismatch, intervening buttons and missing counterpart do not become matched pairs',()=>{const rows=pair('p');rows.filter(r=>r.variant==='menu-floating').forEach(r=>r.input_mode='native');assert.equal(boundaryAnalysis(rows).timing.length,0);assert.equal(boundaryAnalysis(rows).unmatched,2);rows.forEach(r=>r.condition=r.variant+'-between');assert.equal(boundaryAnalysis(rows).nControls,0);});
test('few people do not produce a misleading zero-width CI',()=>{const a=bootstrapMean([10,10,10]);assert.equal(a.low,null);assert.equal(a.mean,10);});
test('unrecognized and duplicate imported records are counted and never mutated',()=>{const r=row('p',0),a=cleanRows([r,r,{...r,id:'bad',acquisition_ms:NaN}]);assert.equal(a.rows.length,1);assert.equal(a.invalid,1);assert.equal(a.duplicates,1);assert.equal(runKey(r),'p:r1');});
