/** Reusable Vega-Lite specifications. Data is passed in; no DOM or experiment logic here. */
export const SCHEMA='https://vega.github.io/schema/vega-lite/v6.json';
export const theme={background:'transparent',font:'Arial',view:{stroke:null},axis:{labelColor:'#596563',titleColor:'#414b49',gridColor:'#e9ece7',domain:false,tickColor:'#cbd1cb',titleFontWeight:500,labelFontSize:11,titleFontSize:12,titlePadding:12},legend:{labelColor:'#596563',title:null,orient:'bottom',symbolType:'circle'}};
const base=(height=230)=>({$schema:SCHEMA,width:'container',height,autosize:{type:'fit',contains:'padding'},config:theme});
const tooltip=[{field:'participant_label',title:'Participant'},{field:'run_number',title:'Run'},{field:'distance',title:'Distance (CSS px)',format:'.1f'},{field:'target_w',title:'Target width (CSS px)',format:'.1f'},{field:'target_h',title:'Target height (CSS px)',format:'.1f'},{field:'approach_width',title:'Size along approach (CSS px)',format:'.1f'},{field:'index_difficulty',title:'Difficulty (bits)',format:'.2f'},{field:'acquisition_ms',title:'Acquisition (ms)',format:'.0f'},{field:'hit',title:'Hit'},{field:'variant',title:'Condition'}];
const stageShape={field:'task',type:'nominal',title:'Stage',scale:{domain:['horizontal','circles','interfaces'],range:['square','circle','diamond']},legend:{labelExpr:"{'horizontal':'Horizontal','circles':'Circles','interfaces':'Interfaces'}[datum.label]"}};
const stageDash={field:'task',type:'nominal',title:'Stage',scale:{domain:['horizontal','circles','interfaces'],range:[[1,0],[6,3],[2,3]]},legend:{labelExpr:stageShape.legend.labelExpr,title:'Trendline',symbolType:'stroke'}};
export function scatterSpec({height=300,extent=2000,x='index_difficulty',xMax=7}={}){return heroSpec({height,extent,x,xMax,classroom:false});}
export function heroSpec({height=320,extent=2000,x:field='index_difficulty',xMax=7,classroom=true}={}){
  const x={field,type:'quantitative',title:null,scale:{domain:[0,xMax]},axis:{tickCount:6,format:field==='index_difficulty'?'.1f':'.0f'}};
  const y={field:'acquisition_ms',type:'quantitative',title:'Acquisition time (ms)',scale:{domain:[0,extent]}};
  const color=classroom?{field:'student_color',type:'nominal',scale:null,legend:null}:{value:'#387d87'};
  return {...base(height),resolve:{legend:{shape:'independent',strokeDash:'independent'}},params:[{name:'focusStudent',value:''}],layer:[
    {params:[{name:'selectedPerson',select:{type:'point',fields:['dataset_id'],on:'click',clear:'dblclick'}}],data:{name:'trials'},
      mark:{type:'point',size:44,strokeWidth:1.3},encoding:{x,y,shape:stageShape,fill:classroom?{condition:{test:'datum.hit',...color},value:'transparent'}:{condition:{test:'datum.hit',value:'#387d87'},value:'transparent'},stroke:color,
      opacity:{condition:{test:"!focusStudent || datum.dataset_id === focusStudent",value:.55},value:.06},tooltip}},
    {data:{name:'means'},mark:{type:'point',filled:true,size:100,stroke:'white',strokeWidth:1},encoding:{x,y,shape:{...stageShape,legend:null},color,opacity:{condition:{test:"!focusStudent || datum.dataset_id === focusStudent",value:.9},value:.08},tooltip:[...tooltip,{field:'n',title:'Successful first attempts'}]}},
    {data:{name:'fit'},mark:{type:'line',strokeWidth:2,color:'#283936',clip:true},encoding:{x,y,strokeDash:stageDash,detail:{field:'series'},tooltip:[{field:'task',title:'Stage'},{field:'label',title:'Settings'},{field:'n',title:'Successful attempts'},{field:'r2',title:'R²',format:'.2f'}]}},
    ...(classroom?[{data:{name:'selectedFit'},mark:{type:'line',strokeWidth:5,color:'#fff',clip:true},encoding:{x,y,strokeDash:{...stageDash,legend:null},detail:{field:'series'}}},{data:{name:'selectedFit'},mark:{type:'line',strokeWidth:3,clip:true},encoding:{x,y,color:{field:'student_color',type:'nominal',scale:null,legend:null},strokeDash:{...stageDash,legend:null},detail:{field:'series'},tooltip:[{field:'task',title:'Selected run fit'},{field:'n',title:'Successful attempts'},{field:'r2',title:'R²',format:'.2f'}]}}]:[])
  ]};
}
export function pathSpec(height=190){return{...base(height),data:{name:'paths'},layer:[
  {data:{values:[{}]},mark:{type:'rule',color:'#b8c3d4',strokeDash:[4,4]},encoding:{x:{datum:1,type:'quantitative'}}},
  {mark:{type:'line',strokeWidth:1.6,opacity:.55},encoding:{x:{field:'along',type:'quantitative',title:'Progress toward target (1 = center)',axis:{tickCount:6,format:'.1f'},scale:{domain:[-.1,1.3]}},y:{field:'across',type:'quantitative',title:'Deviation (CSS px)',axis:{format:'.0f',tickCount:5}},detail:{field:'id'},order:{field:'order'},color:{field:'outcome',scale:{domain:['Hit','Miss'],range:['#387d87','#bd5b2f']},legend:null},tooltip:[{field:'time',title:'Time (ms)',format:'.0f'}]}}
]};}
export function speedSpec(height=190){return{...base(height),data:{name:'speeds'},mark:{type:'line',opacity:.6,strokeWidth:1.5,color:'#387d87'},encoding:{x:{field:'time',type:'quantitative',title:'Time since target activation (ms)'},y:{field:'speed',type:'quantitative',title:'Cursor speed (CSS px/s)'},detail:{field:'id'},order:{field:'time'},tooltip:[{field:'time',format:'.0f'},{field:'speed',format:'.0f'}]}};}
export function endpointsSpec(shape='rect',extent=2,height=190){
  const target=shape==='circle'?Array.from({length:65},(_,i)=>({x:Math.cos(i*2*Math.PI/64),y:Math.sin(i*2*Math.PI/64),order:i})):[{x:-1,y:-1,order:0},{x:1,y:-1,order:1},{x:1,y:1,order:2},{x:-1,y:1,order:3},{x:-1,y:-1,order:4}];
  const enc={x:{field:'x',type:'quantitative',title:'Horizontal / half-width',scale:{domain:[-extent,extent]}},y:{field:'y',type:'quantitative',title:'Vertical / half-height',scale:{domain:[-extent,extent],reverse:true}}};
  return{...base(height),layer:[{data:{values:target},mark:{type:'line',color:'#a7b6cd',strokeWidth:1.5},encoding:{...enc,order:{field:'order'}}},{data:{name:'endpoints'},mark:{type:'point',filled:true,size:44,opacity:.65},encoding:{...enc,color:{field:'outcome',scale:{domain:['Hit','Miss'],range:['#387d87','#bd5b2f']},legend:null},tooltip:[{field:'trial'},{field:'outcome'},{field:'acquisition_ms',format:'.0f'}]}}]};
}
export function boundarySpec({height=230,yMax=null}={}){const y={field:'acquisition_ms',type:'quantitative',title:'Mean acquisition time (ms)',scale:yMax===null?{zero:true}:{domain:[0,yMax]}};return{...base(height),params:[{name:'focusStudent',value:''}],data:{name:'boundaries'},layer:[
  {transform:[{joinaggregate:[{op:'count',as:'pair_count'}],groupby:['comparison_key']},{filter:'datum.pair_count === 2'},
    {aggregate:[{op:'mean',field:'acquisition_ms',as:'acquisition_ms'},{op:'count',as:'participants'}],groupby:['summary_key','variant','order']}],
    mark:{type:'line',strokeWidth:3,color:'#283936',clip:true,point:{filled:true,size:80}},encoding:{x:{field:'variant',type:'nominal',sort:['menu-floating','menu-edge','corner-floating','corner-edge']},y,detail:{field:'summary_key'},order:{field:'order'},tooltip:[{field:'variant'},{field:'acquisition_ms',title:'Paired participant mean (ms)',format:'.0f'},{field:'participants',title:'Complete run pairs'}]}},
  {mark:{type:'line',color:'#8492a8',clip:true},encoding:{x:{field:'variant',type:'nominal',sort:['menu-floating','menu-edge','corner-floating','corner-edge'],title:null,axis:{labelAngle:-18,labelExpr:"{'menu-floating':'Menu: free','menu-edge':'Menu: edge','corner-floating':'Window: free','corner-edge':'Window: edges'}[datum.label]"}},y,detail:{field:'comparison_key'},order:{field:'order'},opacity:{condition:{test:"!focusStudent || datum.dataset_id === focusStudent",value:.6},value:.06}}},
  {params:[{name:'selectedPerson',select:{type:'point',fields:['dataset_id'],on:'click',clear:'dblclick'}}],mark:{type:'point',filled:true,size:66,color:'#387d87',clip:true},encoding:{x:{field:'variant',type:'nominal',sort:['menu-floating','menu-edge','corner-floating','corner-edge']},y,opacity:{condition:{test:"!focusStudent || datum.dataset_id === focusStudent",value:.95},value:.08},tooltip:[{field:'dataset_label',title:'Student run'},{field:'variant'},{field:'app_version',title:'Protocol version'},{field:'acquisition_ms',format:'.0f'},{field:'error_rate',title:'First-attempt error rate',format:'.0%'},{field:'n',title:'First attempts'},{field:'excluded_time',title:'Slow successful trials omitted'}]}}
]};}
