/** DOM report: labels from sessions/data always go through textContent. */
import {taskLabels} from './study.js';
const number=(v,d=1)=>Number.isFinite(v)?v.toLocaleString('en-US',{maximumFractionDigits:d,minimumFractionDigits:d}):'—';
const interval=(lo,hi,d=1)=>Number.isFinite(lo)&&Number.isFinite(hi)?`[${number(lo,d)}, ${number(hi,d)}]`:'Not estimated';
function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function table(headers,rows){const wrapper=el('div',undefined,'study-table-wrap'),t=el('table'),head=el('thead'),tr=el('tr');for(const h of headers)tr.append(el('th',h));head.append(tr);t.append(head);const body=el('tbody');for(const cells of rows){const row=el('tr');for(const c of cells)row.append(el('td',String(c)));body.append(row);}t.append(body);wrapper.append(t);return wrapper;}
export function renderReport(root,study,{title='',receivedAt='',frozen=false}={}){
  root.replaceChildren();const d=study.dataset;
  root.append(el('h2','Session analysis'),el('p',`${title||'Current dataset'}${receivedAt?' · snapshot '+new Date(receivedAt).toLocaleTimeString():''}${frozen?' · frozen':''}`, 'muted'));
  root.append(el('p',`${d.people} participant identities · ${d.runs} runs · ${d.first} first attempts · ${d.misses} misses (${number(d.first?100*d.misses/d.first:null)}%). ${d.invalid} invalid rows excluded; ${d.duplicates} duplicate rows ignored. Protocol versions: ${d.protocols.join(', ')}.`));
  const cutoff=study.cutoff===null?'All durations':`${number(study.cutoff/1000,2)} s`;
  root.append(el('p',`Reference: all valid recorded durations, successful first attempts for timing, ${study.perturbation} pointer. Charts: ${cutoff}; ${d.hidden} finite-target first attempts hidden. Selection and panel layout do not change the session-level reference analysis.`, 'study-notice'));
  root.append(el('h3','Fitts relationships and cutoff sensitivity'));
  root.append(el('p','Each participant contributes equal total weight within a stage/input group. Shading is a pointwise 95% participant-cluster bootstrap interval for the fitted mean (2,000 resamples), not a prediction interval for individual clicks. Repeat runs stay inside their participant cluster. Intervals are withheld below four participants; even larger classroom samples provide limited precision.'));
  const current=new Map(study.filtered.fits.map(f=>[f.key,f]));
  root.append(table(['Stage / settings','People / runs / hits','Reference slope (ms/bit)','95% interval','Intercept (ms)','Intercept 95% interval','Weighted R²','Filtered slope','Filtered 95% interval'],study.reference.fits.map(f=>{
    const c=current.get(f.key);return[taskLabels[f.task]+' · '+f.settings,`${f.nPeople} / ${f.nRuns} / ${f.nTrials}`,number(f.b),interval(f.bLow,f.bHigh),number(f.a),interval(f.aLow,f.aHigh),number(f.r2,2),number(c?.b),interval(c?.bLow,c?.bHigh)];
  })));
  if(!study.reference.fits.length)root.append(el('p','No stage/input group has enough successful attempts and geometric variation for a line yet.'));
  root.append(el('p','Intercepts describe an extrapolation to zero difficulty and should not be interpreted as measured reaction times. The combined view uses the same dimensionless difficulty definition across stages; it still fits separate coefficients because task mechanics and input paths can differ.'));
  root.append(el('h3','Paired boundary differences'));
  root.append(el('p','Positive values mean a benefit from the boundary: free minus bounded time, or free minus bounded first-attempt miss rate. Free/edge summaries are paired within a run and identical protocol/input settings; repeated run differences are averaged within participant before the equal-participant mean and bootstrap. Timing pairs require a retained successful first attempt on each side; “usable pair” does not assert completion of the entire exercise.'));
  const cutoffGroups=new Map(study.boundary.timing.map(g=>[g.key,g]));
  root.append(table(['Comparison / settings','People / run pairs','Free / bounded (ms)','Reference saved (ms)','95% interval','Mean saved (%)','Filtered saved (ms)','Filtered 95% interval'],study.boundaryReference.timing.map(g=>{
    const s=g.summary,c=cutoffGroups.get(g.key)?.summary;return[(g.pair==='menu'?'Menu':'Window')+' · '+g.settings,`${s.n} / ${s.nRuns}`,`${number(s.free)} / ${number(s.edge)}`,number(s.mean),interval(s.low,s.high),number(s.percent),number(c?.mean),interval(c?.low,c?.high)];
  })));
  for(const g of study.boundaryReference.timing){const s=g.summary;root.append(el('p',`${g.pair==='menu'?'Menu':'Window'} (${g.settings}): the observed untrimmed paired difference is ${number(Math.abs(s.mean))} ms ${s.mean>=0?'faster':'slower'} with the boundary. ${s.low===null?'The participant sample is too small for a displayed interval.':s.low<=0&&s.high>=0?'The interval spans both a possible benefit and a possible cost.':'The displayed interval lies '+(s.low>0?'above':'below')+' zero.'} Free always came first, so this comparison combines boundary and order/practice effects.`));}
  root.append(el('h3','Accuracy: all first attempts'));
  root.append(table(['Comparison / settings','People / run pairs','Free misses (%)','Bounded misses (%)','Misses reduced (points)','95% interval'],study.boundaryReference.accuracy.map(g=>{const s=g.summary;return[(g.pair==='menu'?'Menu':'Window')+' · '+g.settings,`${s.n} / ${s.nRuns}`,number(s.free),number(s.edge),number(s.mean),interval(s.low,s.high)];})));
  root.append(el('p',`Accuracy includes slow and failed first attempts, independent of the timing cutoff. ${study.boundaryReference.unmatched} run/input/target groups lack an observed opposite side. Timing and accuracy can have different usable samples; every table reports its own denominator.`));
  const log=el('details');log.append(el('summary','Log-time sensitivity (exploratory)'));
  log.append(el('p','Weighted regression of natural-log acquisition time against difficulty, using positive untrimmed successful first-attempt durations. Slope units and R² refer to log time and cannot be compared directly with millisecond-model R². This alternative is a sensitivity check, not an automatic declaration that one model is correct.'));
  log.append(table(['Stage / settings','People','ln(ms) per bit','Descriptive log R²'],study.logSensitivity.fits.map(f=>[taskLabels[f.task]+' · '+f.settings,f.nPeople,number(f.b,3),number(f.r2,2)])));root.append(log);
  root.append(el('h3','Design and limitations'));
  root.append(el('p','This is a browser-based teaching demonstration and a convenience sample. Participant identities refer to saved browser credentials, not a verified roster of distinct people. Acquisition time runs from target activation to primary-button press and includes cue response and correction. Successful retries contain cumulative time and are excluded from first-attempt timing regressions; they remain in raw exports and path inspection.'));
  root.append(el('p','Hard-edge trials have no scalar Fitts index in this implementation and are analyzed through paired contrasts. Menu/window free conditions always precede bounded conditions. Devices, physical scale, browser latency, strategies, incomplete sets, and unbalanced participation can influence the results. “Normal pointer” does not mean native/system input: captured and native records remain separate fit groups.'));
  root.append(el('p','The untrimmed reference and current cutoff are reported side by side; neither is presented as preregistered. Interactively selected cutoffs and repeated live inspection make these exploratory estimates. Bootstrap intervals do not correct order confounding, selection bias, or small-sample uncertainty, and are not simultaneous confidence bands. No p-value, causal boundary claim, mixed-effects fit, or standardized throughput score is asserted. Exact-condition repetitions are sparse for reliable endpoint-based throughput.'));
  const refs=el('p');refs.append(document.createTextNode('Methods and reproducible implementation: '));const link=el('a','Analysis guide');link.href='./docs/ANALYSIS.html';refs.append(link);root.append(refs);
}
